### PR TITLE
Prepare to update branch to main

### LINKED ISSUE #32: Rename default branch to main
Specific instructions can be viewed here: https://github.com/github/renaming#rename-existing

- [ ] Code owner needs to rename default branch from master to main
- [ ] If you have a fork and/or local clone, here are the steps you need to take:
  - Navigate to your fork on GitHub, go to the Settings tab, then the Branches tab, and then under Default branch, click the pencil icon to rename the default branch to main.

- [ ] If you have a local clone, run the following commands in Git Bash:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
Fixes #32

### CODE REVIEW

**Review by Keboo — APPROVED** [review]

**Comment by BenjaminMichaelis** [comment]
After merging, is it ok to switch default branch from master to main? @Keboo

**Comment by Keboo** [comment]
No objections, just double check to make sure any branch policies are also recreated.

**Comment by BenjaminMichaelis** [comment]
@Keboo any idea on why this continuous integration won't finish? I can't merge until it does

**Comment by Keboo** [comment]
ouch, that looks like it is pointed at a really old appveyor pipelines (long since dead). I removed the web hook for it

**Comment by Keboo** [comment]
There, removed the appveyor status check requirement. Looks like just the build failure is blocking now.

**Comment by BenjaminMichaelis** [comment]
Looks like the last build on main was already failing so probably due to a previous issue as the issues listing for failure are the same as the previous build on main

**Comment by BenjaminMichaelis** [comment]
@Keboo Looks like the last build on main was already failing so probably due to a previous issue as the issues listing for failure are the same as the previous build on main so I could just keep the failure and merge and just switch the branches since it seems like this project isn't being kept the most up to date unless we want to try and fix it first.

**Comment by Keboo** [comment]
I am fine with that, but lets log an issue to get it fixed.

**Pull request merged**
